paths:
  element_data: data/element_params/Data_keV.xlsx
  form_factors: data/form_factors/form_factor_coherent_scatter.xlsx
  absorption_dir: data/absorption_coeffs
  output_dir: results/kaguya

concentration_cols: ["A16"]

all_matrix_elements: ["N","O","Na","Mg","Al","Si","P","S","Cl","K","Ca","Ti","Cr","Mn","Fe","Ni"]
fluorescence_elements: ["Mg","Al","Si","P","S","K","Ca","Ti","Cr","Mn","Fe"]

theta: 0.0
phi: 0.0
altitude: 1e7
distance_sun_AU: 1.0
footprint: 4e12
